"""Parent portal SQLAlchemy model.

Covers: parent_report_snapshots
"""

import uuid
from datetime import date, datetime
from typing import Any

from sqlalchemy import Date, ForeignKey, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, UUIDMixin


class ParentReportSnapshot(Base, UUIDMixin):
    """Weekly parent narrative."""

    __tablename__ = "parent_report_snapshots"

    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    narrative: Mapped[str] = mapped_column(Text, nullable=False)
    # Plain language, ~150 words, generated by Gemini Flash
    gap_summary: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    # [{"subtopic": "Quadratic Equations", "mastery": 0.45,
    #   "label": "Developing", "trend": "improving"}]
    improvements: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    # top 2 subtopics that improved this week vs last snapshot
    needs_work: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    # top 2 subtopics still below mastery threshold
    email_sent_at: Mapped[datetime | None]
    generated_at: Mapped[datetime]

    __table_args__ = (UniqueConstraint("student_id", "week_start", name="prp_student_week_unique"),)
