"""Study plan SQLAlchemy models.

Covers: study_plans, study_plan_resources, study_plan_quizzes
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import Boolean, CheckConstraint, Enum, ForeignKey, Integer, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class StudyPlanStatus:
    """Study plan status constants."""

    GENERATING = "GENERATING"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class ResourceType:
    """Resource type constants."""

    VIDEO = "VIDEO"
    ARTICLE = "ARTICLE"
    INTERACTIVE = "INTERACTIVE"


class StudyPlan(Base, UUIDMixin, TimestampMixin):
    """One study plan per student per subtopic per class."""

    __tablename__ = "study_plans"

    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    subtopic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("subtopics.id", ondelete="RESTRICT"),
        nullable=False,
    )
    class_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("classes.id", ondelete="CASCADE"),
        nullable=False,
    )
    assigned_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    status: Mapped[str] = mapped_column(
        Enum(
            StudyPlanStatus.GENERATING,
            StudyPlanStatus.ACTIVE,
            StudyPlanStatus.COMPLETED,
            StudyPlanStatus.ABANDONED,
            name="study_plan_status",
            native_enum=False,
        ),
        nullable=False,
        default=StudyPlanStatus.GENERATING,
    )
    assigned_at: Mapped[datetime]
    started_at: Mapped[datetime | None]
    completed_at: Mapped[datetime | None]

    # ORM relationships for eager loading (prevents N+1 queries in list endpoints)
    resources: Mapped[list["StudyPlanResource"]] = relationship(
        "StudyPlanResource",
        cascade="all, delete-orphan",
        order_by="StudyPlanResource.order_index",
    )
    quiz: Mapped["StudyPlanQuiz | None"] = relationship(
        "StudyPlanQuiz",
        cascade="all, delete-orphan",
        uselist=False,
    )


class StudyPlanResource(Base, UUIDMixin, TimestampMixin):
    """Curated external resources (2-3 per plan)."""

    __tablename__ = "study_plan_resources"

    plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("study_plans.id", ondelete="CASCADE"),
        nullable=False,
    )
    resource_type: Mapped[str] = mapped_column(
        Enum(
            ResourceType.VIDEO,
            ResourceType.ARTICLE,
            ResourceType.INTERACTIVE,
            name="resource_type",
            native_enum=False,
        ),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    duration_seconds: Mapped[int | None]
    alignment_score: Mapped[float | None]
    # cosine_sim(resource_embed, subtopic.embedding). Threshold: > 0.72 to be included.
    order_index: Mapped[int] = mapped_column(Integer, nullable=False)
    is_watched: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    watched_at: Mapped[datetime | None]

    __table_args__ = (
        CheckConstraint(
            "alignment_score IS NULL OR (alignment_score BETWEEN 0.0 AND 1.0)",
            name="chk_spr_alignment",
        ),
    )


class StudyPlanQuiz(Base, UUIDMixin):
    """AI-generated quiz. One quiz per study plan."""

    __tablename__ = "study_plan_quizzes"

    plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("study_plans.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    questions: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    # 5 questions generated by quiz_generator.py using subtopic.embedding for RAG
    # [{
    #   "index": 0, "question_text": "...", "type": "MCQ",
    #   "options": [{"key": "A", "text": "..."},...],
    #   "correct_answer": "A", "explanation": "..."
    # }]
    student_answers: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB)
    # [{index: 0, answer: "A", is_correct: true, score: 1.0}]
    # NULL until student submits
    score: Mapped[float | None]
    completed_at: Mapped[datetime | None]
    created_at: Mapped[datetime]

    __table_args__ = (
        CheckConstraint(
            "score IS NULL OR (score BETWEEN 0.0 AND 1.0)",
            name="chk_spq_score",
        ),
    )
