[mypy]
python_version = 3.12

strict = true
no_implicit_optional = true
warn_unused_configs = true
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true

disallow_any_generics = true

pretty = true
show_error_codes = true

ignore_missing_imports = false

plugins = pydantic.mypy


[mypy-pgvector.*]
ignore_missing_imports = true

[mypy-celery.*]
ignore_missing_imports = true
ignore_errors = true

[mypy-jose.*]
ignore_missing_imports = true
ignore_errors = true

[mypy-redis.*]
ignore_missing_imports = true
ignore_errors = true

[mypy-redis.asyncio]
ignore_missing_imports = true
ignore_errors = true

[mypy-app.api.v1.routes.health]
warn_unused_ignores = false

[mypy-passlib.*]
ignore_missing_imports = true
ignore_errors = true

[mypy-app.tests.*]
disallow_any_generics = false
warn_unused_ignores = false
disable_error_code = type-var

[mypy-unittest.mock]
ignore_errors = true

[mypy-pytest.*]
ignore_errors = true
