[mypy]
python_version = 3.12
strict = true
ignore_missing_imports = true
warn_unused_configs = false
disallow_untyped_defs = false

[mypy-pydantic.*]
ignore_missing_imports = true

[mypy-pydantic_settings.*]
ignore_missing_imports = true

[mypy-redis.*]
ignore_missing_imports = true
