"""initial schema

Revision ID: 2548e64cec42
Revises: 
Create Date: 2026-02-02 12:57:16.478404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2548e64cec42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('points_required', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('curricula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_curricula_id'), 'curricula', ['id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_level'), 'grades', ['level'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('yearly_discount', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canonical_code', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('bloom_taxonomy_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='chk_topic_difficulty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_code')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('PARENT', 'STUDENT', 'TEACHER', 'SCHOOL_ADMIN', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('billing_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_expiry', sa.String(length=10), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=100), nullable=True),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_info_id'), 'billing_info', ['id'], unique=False)
    op.create_table('curriculum_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('standard_code', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('recommended_weeks', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='chk_ct_difficulty'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'grade_id', 'subject_id', 'topic_id', name='uq_curriculum_grade_subject_topic')
    )
    op.create_index('idx_ct_curriculum_grade_subject', 'curriculum_topics', ['curriculum_id', 'grade_id', 'subject_id'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_curriculum_id'), 'curriculum_topics', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_grade_id'), 'curriculum_topics', ['grade_id'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_id'), 'curriculum_topics', ['id'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_subject_id'), 'curriculum_topics', ['subject_id'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_topic_id'), 'curriculum_topics', ['topic_id'], unique=False)
    op.create_table('plan_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_description', sa.Text(), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_features_id'), 'plan_features', ['id'], unique=False)
    op.create_table('plan_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_subjects_id'), 'plan_subjects', ['id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('has_completed_assessment', sa.Boolean(), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_format', sa.String(length=50), nullable=True),
    sa.Column('preferred_session_length', sa.Integer(), nullable=True),
    sa.Column('learning_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('motivation_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registration_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_grade_id'), 'student_profiles', ['grade_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_profiles_parent_id'), 'student_profiles', ['parent_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('subtopics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canonical_code', sa.String(length=50), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('bloom_taxonomy_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='chk_subtopic_difficulty'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'canonical_code', name='uq_topic_subtopic_code')
    )
    op.create_index('idx_subtopic_topic_sequence', 'subtopics', ['topic_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_subtopics_id'), 'subtopics', ['id'], unique=False)
    op.create_index(op.f('ix_subtopics_topic_id'), 'subtopics', ['topic_id'], unique=False)
    op.create_table('topic_prerequisites',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_topic_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('topic_id <> prerequisite_topic_id', name='chk_no_self_prereq'),
    sa.ForeignKeyConstraint(['prerequisite_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'prerequisite_topic_id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('assessment_type', sa.Enum('DIAGNOSTIC', 'PROGRESS', 'FINAL', 'TOPIC_SPECIFIC', name='assessmenttype'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='assessmentstatus'), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_status_created', 'assessments', ['status', 'created_at'], unique=False)
    op.create_index('idx_assessment_student_subject', 'assessments', ['student_id', 'subject_id'], unique=False)
    op.create_index(op.f('ix_assessments_grade_id'), 'assessments', ['grade_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_student_id'), 'assessments', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessments_subject_id'), 'assessments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_assessments_topic_id'), 'assessments', ['topic_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('subtopic_id', sa.UUID(), nullable=True),
    sa.Column('learning_objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), server_default='15', nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('prerequisite_topic_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=True),
    sa.Column('generation_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='chk_mc_difficulty'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mc_grade_subject', 'courses', ['grade_id', 'subject_id'], unique=False)
    op.create_index('idx_mc_subject_topic', 'courses', ['subject_id', 'topic_id'], unique=False)
    op.create_index(op.f('ix_courses_grade_id'), 'courses', ['grade_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_subject_id'), 'courses', ['subject_id'], unique=False)
    op.create_index(op.f('ix_courses_subtopic_id'), 'courses', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_courses_topic_id'), 'courses', ['topic_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    op.create_table('question_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subtopic_id', sa.UUID(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Float(), nullable=True),
    sa.Column('bloom_taxonomy_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_time_seconds', sa.Integer(), nullable=True),
    sa.Column('prerequisites', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canonical_form', sa.Text(), nullable=False),
    sa.Column('problem_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qb_grade_subject', 'question_bank', ['grade_id', 'subject_id'], unique=False)
    op.create_index('idx_qb_subject_topic_difficulty', 'question_bank', ['subject_id', 'topic_id', 'difficulty_level'], unique=False)
    op.create_index(op.f('ix_question_bank_grade_id'), 'question_bank', ['grade_id'], unique=False)
    op.create_index(op.f('ix_question_bank_id'), 'question_bank', ['id'], unique=False)
    op.create_index(op.f('ix_question_bank_subject_id'), 'question_bank', ['subject_id'], unique=False)
    op.create_index(op.f('ix_question_bank_subtopic_id'), 'question_bank', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_question_bank_topic_id'), 'question_bank', ['topic_id'], unique=False)
    op.create_table('student_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_badges_id'), 'student_badges', ['id'], unique=False)
    op.create_table('student_knowledge_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subtopic_id', sa.UUID(), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessment_count', sa.Integer(), nullable=True),
    sa.Column('total_questions_attempted', sa.Integer(), nullable=True),
    sa.Column('total_questions_correct', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skp_needs_review', 'student_knowledge_profiles', ['student_id', 'needs_review'], unique=False)
    op.create_index('idx_skp_student_subject', 'student_knowledge_profiles', ['student_id', 'subject_id'], unique=False)
    op.create_index('idx_skp_student_topic', 'student_knowledge_profiles', ['student_id', 'topic_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_profiles_id'), 'student_knowledge_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_profiles_student_id'), 'student_knowledge_profiles', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_profiles_subject_id'), 'student_knowledge_profiles', ['subject_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_profiles_subtopic_id'), 'student_knowledge_profiles', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_student_knowledge_profiles_topic_id'), 'student_knowledge_profiles', ['topic_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'TRIAL', 'PAST_DUE', name='subscriptionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'DISPUTED', name='paymentstatus'), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_id'), 'tutor_sessions', ['id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_bank_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aq_assessment_question', 'assessment_questions', ['assessment_id', 'question_number'], unique=False)
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_id'), 'assessment_questions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_question_bank_id'), 'assessment_questions', ['question_bank_id'], unique=False)
    op.create_table('assessment_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('study_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mastery_table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessment_reports_id'), 'assessment_reports', ['id'], unique=False)
    op.create_table('course_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.Enum('INTRO', 'EXPLANATION', 'EXAMPLE', 'PRACTICE', 'SUMMARY', name='coursesectiontype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.Enum('VIDEO', 'AUDIO', 'TEXT', 'QUIZ', 'INTERACTIVE', 'ASSIGNMENT', name='coursecontenttype'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcs_course_position', 'course_sections', ['course_id', 'position'], unique=False)
    op.create_index(op.f('ix_course_sections_course_id'), 'course_sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_sections_id'), 'course_sections', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'DISPUTED', name='paymentstatus'), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('student_course_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('sections_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questions_answered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scp_student_course', 'student_course_progress', ['student_id', 'course_id'], unique=False)
    op.create_index('idx_scp_student_status', 'student_course_progress', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_student_course_progress_course_id'), 'student_course_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_progress_id'), 'student_course_progress', ['id'], unique=False)
    op.create_index(op.f('ix_student_course_progress_student_id'), 'student_course_progress', ['student_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_weeks', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sp_student_status', 'study_plans', ['student_id', 'status'], unique=False)
    op.create_index(op.f('ix_study_plans_assessment_id'), 'study_plans', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_study_plans_id'), 'study_plans', ['id'], unique=False)
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_table('trial_extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('extended_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('original_trial_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_trial_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extension_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extended_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_extensions_id'), 'trial_extensions', ['id'], unique=False)
    op.create_table('tutor_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_interactions_id'), 'tutor_interactions', ['id'], unique=False)
    op.create_table('course_question_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('question_bank_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcql_course_position', 'course_question_links', ['course_id', 'position'], unique=False)
    op.create_index(op.f('ix_course_question_links_course_id'), 'course_question_links', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_question_links_id'), 'course_question_links', ['id'], unique=False)
    op.create_index(op.f('ix_course_question_links_question_bank_id'), 'course_question_links', ['question_bank_id'], unique=False)
    op.create_table('study_plan_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_plan_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subtopic_id', sa.UUID(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('suggested_duration_mins', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('custom_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spl_plan_sequence', 'study_plan_courses', ['study_plan_id', 'sequence_order'], unique=False)
    op.create_index('idx_spl_plan_week', 'study_plan_courses', ['study_plan_id', 'week'], unique=False)
    op.create_index(op.f('ix_study_plan_courses_course_id'), 'study_plan_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_plan_courses_id'), 'study_plan_courses', ['id'], unique=False)
    op.create_index(op.f('ix_study_plan_courses_study_plan_id'), 'study_plan_courses', ['study_plan_id'], unique=False)
    op.create_index(op.f('ix_study_plan_courses_subtopic_id'), 'study_plan_courses', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_study_plan_courses_topic_id'), 'study_plan_courses', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plan_courses_topic_id'), table_name='study_plan_courses')
    op.drop_index(op.f('ix_study_plan_courses_subtopic_id'), table_name='study_plan_courses')
    op.drop_index(op.f('ix_study_plan_courses_study_plan_id'), table_name='study_plan_courses')
    op.drop_index(op.f('ix_study_plan_courses_id'), table_name='study_plan_courses')
    op.drop_index(op.f('ix_study_plan_courses_course_id'), table_name='study_plan_courses')
    op.drop_index('idx_spl_plan_week', table_name='study_plan_courses')
    op.drop_index('idx_spl_plan_sequence', table_name='study_plan_courses')
    op.drop_table('study_plan_courses')
    op.drop_index(op.f('ix_course_question_links_question_bank_id'), table_name='course_question_links')
    op.drop_index(op.f('ix_course_question_links_id'), table_name='course_question_links')
    op.drop_index(op.f('ix_course_question_links_course_id'), table_name='course_question_links')
    op.drop_index('idx_mcql_course_position', table_name='course_question_links')
    op.drop_table('course_question_links')
    op.drop_index(op.f('ix_tutor_interactions_id'), table_name='tutor_interactions')
    op.drop_table('tutor_interactions')
    op.drop_index(op.f('ix_trial_extensions_id'), table_name='trial_extensions')
    op.drop_table('trial_extensions')
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_assessment_id'), table_name='study_plans')
    op.drop_index('idx_sp_student_status', table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_student_course_progress_student_id'), table_name='student_course_progress')
    op.drop_index(op.f('ix_student_course_progress_id'), table_name='student_course_progress')
    op.drop_index(op.f('ix_student_course_progress_course_id'), table_name='student_course_progress')
    op.drop_index('idx_scp_student_status', table_name='student_course_progress')
    op.drop_index('idx_scp_student_course', table_name='student_course_progress')
    op.drop_table('student_course_progress')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_course_sections_id'), table_name='course_sections')
    op.drop_index(op.f('ix_course_sections_course_id'), table_name='course_sections')
    op.drop_index('idx_mcs_course_position', table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_index(op.f('ix_assessment_reports_id'), table_name='assessment_reports')
    op.drop_table('assessment_reports')
    op.drop_index(op.f('ix_assessment_questions_question_bank_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_index('idx_aq_assessment_question', table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_tutor_sessions_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_student_knowledge_profiles_topic_id'), table_name='student_knowledge_profiles')
    op.drop_index(op.f('ix_student_knowledge_profiles_subtopic_id'), table_name='student_knowledge_profiles')
    op.drop_index(op.f('ix_student_knowledge_profiles_subject_id'), table_name='student_knowledge_profiles')
    op.drop_index(op.f('ix_student_knowledge_profiles_student_id'), table_name='student_knowledge_profiles')
    op.drop_index(op.f('ix_student_knowledge_profiles_id'), table_name='student_knowledge_profiles')
    op.drop_index('idx_skp_student_topic', table_name='student_knowledge_profiles')
    op.drop_index('idx_skp_student_subject', table_name='student_knowledge_profiles')
    op.drop_index('idx_skp_needs_review', table_name='student_knowledge_profiles')
    op.drop_table('student_knowledge_profiles')
    op.drop_index(op.f('ix_student_badges_id'), table_name='student_badges')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_question_bank_topic_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_subtopic_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_subject_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_id'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_grade_id'), table_name='question_bank')
    op.drop_index('idx_qb_subject_topic_difficulty', table_name='question_bank')
    op.drop_index('idx_qb_grade_subject', table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_courses_topic_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_subtopic_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_subject_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_grade_id'), table_name='courses')
    op.drop_index('idx_mc_subject_topic', table_name='courses')
    op.drop_index('idx_mc_grade_subject', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_assessments_topic_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_subject_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_student_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_grade_id'), table_name='assessments')
    op.drop_index('idx_assessment_student_subject', table_name='assessments')
    op.drop_index('idx_assessment_status_created', table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('topic_prerequisites')
    op.drop_index(op.f('ix_subtopics_topic_id'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_id'), table_name='subtopics')
    op.drop_index('idx_subtopic_topic_sequence', table_name='subtopics')
    op.drop_table('subtopics')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_parent_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_grade_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_plan_subjects_id'), table_name='plan_subjects')
    op.drop_table('plan_subjects')
    op.drop_index(op.f('ix_plan_features_id'), table_name='plan_features')
    op.drop_table('plan_features')
    op.drop_index(op.f('ix_curriculum_topics_topic_id'), table_name='curriculum_topics')
    op.drop_index(op.f('ix_curriculum_topics_subject_id'), table_name='curriculum_topics')
    op.drop_index(op.f('ix_curriculum_topics_id'), table_name='curriculum_topics')
    op.drop_index(op.f('ix_curriculum_topics_grade_id'), table_name='curriculum_topics')
    op.drop_index(op.f('ix_curriculum_topics_curriculum_id'), table_name='curriculum_topics')
    op.drop_index('idx_ct_curriculum_grade_subject', table_name='curriculum_topics')
    op.drop_table('curriculum_topics')
    op.drop_index(op.f('ix_billing_info_id'), table_name='billing_info')
    op.drop_table('billing_info')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_grades_level'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_curricula_id'), table_name='curricula')
    op.drop_table('curricula')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
