"""add configurable questions and meta tags

Revision ID: 25b7607b597f
Revises: 287f61b46d66
Create Date: 2026-02-10 09:30:14.024408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '25b7607b597f'
down_revision = '287f61b46d66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('total_questions_configurable', sa.Integer(), nullable=True, server_default=sa.text('20')))
    op.drop_column('assessments', 'grade_id')
    op.drop_index('ix_badges_id', table_name='badges')
    # Check if constraint exists before dropping (may not exist in some environments)
    conn = op.get_bind()
    result = conn.execute(text("""
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_badges_name'
        AND conrelid = 'badges'::regclass
    """))
    if result.fetchone():
        op.drop_constraint('uq_badges_name', 'badges', type_='unique')
    op.drop_column('badges', 'created_at')
    op.drop_column('courses', 'prerequisite_topic_ids')
    op.add_column(
        'courses',
        sa.Column(
            'prerequisite_topic_ids',
            sa.ARRAY(sa.UUID(as_uuid=True)),
            nullable=True
        )
    )
    op.drop_index('ix_curriculum_subjects_curriculum_id', table_name='curriculum_subjects')
    op.drop_index('ix_curriculum_subjects_subject_id', table_name='curriculum_subjects')
    op.add_column('question_bank', sa.Column('meta_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('question_bank', 'prerequisites')
    op.add_column(
        'question_bank',
        sa.Column(
            'prerequisite_topic_ids',
            sa.ARRAY(sa.UUID(as_uuid=True)),
            nullable=True
        )
    )
    op.drop_column('student_profiles', 'learning_profile_version')
    op.drop_column('student_profiles', 'learning_profile_updated_at')
    op.drop_constraint('uq_teachers_user_id', 'teachers', type_='unique')
    op.drop_index('ix_teachers_user_id', table_name='teachers')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_index('ix_teachers_user_id', 'teachers', ['user_id'], unique=False)
    op.create_unique_constraint('uq_teachers_user_id', 'teachers', ['user_id'])
    op.add_column('student_profiles', sa.Column('learning_profile_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('learning_profile_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('question_bank', 'prerequisite_topic_ids')
    op.add_column(
        'question_bank',
        sa.Column(
            'prerequisites',
            sa.ARRAY(sa.UUID()),
            nullable=True
        )
    )
    op.drop_column('question_bank', 'meta_tags')
    op.create_index('ix_curriculum_subjects_subject_id', 'curriculum_subjects', ['subject_id'], unique=False)
    op.create_index('ix_curriculum_subjects_curriculum_id', 'curriculum_subjects', ['curriculum_id'], unique=False)
    op.drop_column('courses', 'prerequisite_topic_ids')
    op.add_column(
        'courses',
        sa.Column(
            'prerequisite_topic_ids',
            sa.ARRAY(sa.UUID()),
            nullable=True
        )
    )
    op.add_column('badges', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_badges_name', 'badges', ['name'])
    op.create_index('ix_badges_id', 'badges', ['id'], unique=False)
    op.add_column('assessments', sa.Column('grade_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    op.drop_column('assessments', 'total_questions_configurable')
    # ### end Alembic commands ###
