"""Re-establish relationship between assessments and QuestionBank

Revision ID: 44788560034a
Revises: cfaeb960aa08
Create Date: 2025-09-27 13:01:26.466545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44788560034a'
down_revision = 'cfaeb960aa08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_questions', sa.Column('knowledge_area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assessment_questions', 'knowledge_areas', ['knowledge_area_id'], ['id'])
    op.drop_column('assessment_questions', 'topic')
    op.drop_column('assessment_questions', 'subtopic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_questions', sa.Column('subtopic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assessment_questions', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessment_questions', type_='foreignkey')
    op.drop_column('assessment_questions', 'knowledge_area_id')
    # ### end Alembic commands ###
