"""Allow nullable student_id for parent-level trials

Revision ID: 71bfcaf277f8
Revises: f606f7d0aaa2
Create Date: 2026-01-21 21:37:08.436242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71bfcaf277f8'
down_revision = 'f606f7d0aaa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
