from enum import Enum

TOTAL_QUESTIONS_PER_ASSESSMENT = 20
ASSESSMENT_MAX_QUESTIONS_PER_SUBTOPIC = 5

# Payment Plan Types
PAYMENT_PLAN_BASIC = "basic"
PAYMENT_PLAN_PREMIUM = "premium"

# Billing Constants
DEFAULT_TRIAL_PERIOD_DAYS = 15
DEFAULT_YEARLY_DISCOUNT_PERCENTAGE = 20.00
BILLING_CYCLE_MONTHLY = "monthly"
BILLING_CYCLE_ANNUAL = "annual"

# Subscription Plan Constants
BASIC_PLAN_PRICE_PER_SUBJECT = 25.00  # $25 per subject per month
PREMIUM_PLAN_PRICE = 85.00  # $85 per month for all subjects