import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlertCircle, BookOpen, Loader2, Sparkles } from "lucide-react";
import { useGenerateMiniCourse } from "../../hooks/useGenerateMiniCourse";
import {
  useCourseStatus,
  type VideoCoverage,
} from "../../hooks/useCourseStatus";
import { useQueryClient } from "@tanstack/react-query";

interface TopicMiniCourseButtonProps {
  topicId: string;
  classId: string;
}

// Non-blocking — video is curated separately by Kaihle Admin, never generated by this
// flow (MCR-T4). Rendered under the primary action, never in place of it.
function VideoCoverageNote({ coverage }: { coverage: VideoCoverage }) {
  if (coverage.total === 0 || coverage.covered >= coverage.total) return null;
  return (
    <p className="text-xs text-brand-muted mt-1">
      {coverage.covered}/{coverage.total} subtopics have video — Kaihle Admin
      curates video separately, this doesn&apos;t block content review.
    </p>
  );
}

type LocalState =
  | "idle" // showing button label determined by DB status
  | "confirming" // 2-second auto-confirm before submitting
  | "pending" // mutation in-flight
  | "simulating" // pulsing badge — content existed, email queued
  | "generating" // pulsing badge — real generation running
  | "error"; // persistent red error state

export function TopicMiniCourseButton({
  topicId,
  classId,
}: TopicMiniCourseButtonProps) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const {
    data: courseStatus,
    dataUpdatedAt,
    isLoading: statusLoading,
  } = useCourseStatus(topicId);
  const mutation = useGenerateMiniCourse();

  const [localState, setLocalState] = useState<LocalState>("idle");
  const [errorMessage, setErrorMessage] = useState<string>("");

  const confirmTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // "ready" can only be reached by finishing a real run — a "View Course" button
  // short-circuits handleClick before "generating" is ever entered, so the old
  // ready-only check never saw a stale "ready" from before the click. "partial" has no
  // such guarantee: it's both the button's OWN idle/entry state (shown as "Generate
  // missing") and a legitimate post-run resting state, so the same cached value can
  // be sitting there both before and after a click. Capturing dataUpdatedAt at the
  // moment "generating" starts, and only auto-completing once a FRESH fetch (newer than
  // that) confirms ready/partial, closes the race where invalidateQueries' refetch
  // hadn't resolved yet and the effect fired on the pre-click stale "partial" —
  // instantly reverting the button to idle before the Celery task had done any work.
  const generatingStartedAtRef = useRef<number>(0);

  useEffect(() => {
    return () => {
      if (confirmTimerRef.current) clearTimeout(confirmTimerRef.current);
    };
  }, []);

  // When real generation completes (status flips from generating → ready/partial),
  // return local state to idle so the resting-state button appears.
  useEffect(() => {
    const settledFresh =
      dataUpdatedAt > generatingStartedAtRef.current &&
      (courseStatus?.status === "ready" || courseStatus?.status === "partial");
    if (settledFresh && localState === "generating") {
      setLocalState("idle");
    }
    if (courseStatus?.status === "failed" && localState === "generating") {
      setLocalState("error");
      setErrorMessage("Generation failed. Our team has been notified.");
    }
  }, [courseStatus?.status, dataUpdatedAt, localState]);

  function handleClick() {
    if (localState !== "idle") return;
    // If already ready, go straight to Course Detail
    if (courseStatus?.status === "ready") {
      navigate(
        `/teacher/content-review/mini-courses/${topicId}?classId=${classId}`,
      );
      return;
    }

    setLocalState("confirming");
    confirmTimerRef.current = setTimeout(() => {
      setLocalState("pending");
      mutation.mutate(topicId, {
        onSuccess: (_data) => {
          // If content already existed → fast path (30s email). Show simulating badge.
          // If real generation → show generating badge and poll via useCourseStatus.
          if (courseStatus?.status === "ready") {
            setLocalState("simulating");
            // Simulating badge shows for 35s (covers the 30s email delay + buffer)
            setTimeout(() => {
              setLocalState("idle");
              queryClient.invalidateQueries({
                queryKey: ["course-status", topicId],
              });
            }, 35_000);
          } else {
            generatingStartedAtRef.current = dataUpdatedAt;
            setLocalState("generating");
            // useCourseStatus polls every 5s when status = generating
            queryClient.invalidateQueries({
              queryKey: ["course-status", topicId],
            });
          }
        },
        onError: () => {
          setLocalState("error");
          setErrorMessage("Something went wrong. Please try again.");
        },
      });
    }, 2000);
  }

  if (statusLoading) {
    return <span className="text-xs text-brand-muted italic">Loading...</span>;
  }

  // Pulsing badge — simulating or real generation in progress
  if (localState === "simulating" || localState === "generating") {
    return (
      <div className="space-y-1">
        <span
          className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold text-brand-gold bg-[#fffbeb] border border-brand-gold/30 animate-pulse"
          aria-live="polite"
          aria-label="Generating mini-course content in the background"
        >
          <Sparkles className="w-3 h-3" aria-hidden="true" />
          Generating content...
        </span>
        <p className="text-xs text-brand-muted">
          You'll be notified by email when it's ready.
        </p>
      </div>
    );
  }

  // Persistent error state
  if (localState === "error" || courseStatus?.status === "failed") {
    return (
      <div className="space-y-1">
        <button
          type="button"
          onClick={() => {
            setLocalState("idle");
            setErrorMessage("");
          }}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold text-white bg-red-600 hover:bg-red-700 transition-colors focus-visible:ring-2 focus-visible:ring-red-500 focus-visible:ring-offset-2"
          aria-label="Generation failed — click to retry"
        >
          <AlertCircle className="w-3.5 h-3.5" aria-hidden="true" />
          Generation failed — Retry
        </button>
        <p className="text-xs text-brand-muted">
          {errorMessage || "Our team has been notified. You can retry above."}
        </p>
      </div>
    );
  }

  // Partial — some content generated, some gaps remain. Amber, not red: most of this
  // topic's content is real and usable, so "Retry" (which reads as "start over") would
  // be misleading. Labeled "Generate missing" to match CourseDetailPage's banner for
  // the same underlying idempotent action (Kilo Code review finding).
  if (courseStatus?.status === "partial" && localState === "idle") {
    return (
      <div className="space-y-1">
        <button
          type="button"
          onClick={handleClick}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold text-brand-gold bg-[#fffbeb] border border-brand-gold/30 hover:bg-brand-gold hover:text-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold focus-visible:ring-offset-2"
          aria-label="Generate missing content for this topic"
        >
          <AlertCircle className="w-3.5 h-3.5" aria-hidden="true" />
          Generate missing
          {courseStatus.gaps_count > 0
            ? ` (${courseStatus.gaps_count} left)`
            : ""}
        </button>
        <p className="text-xs text-brand-muted">
          Most content is ready — a few items are still missing.
        </p>
        {courseStatus.video_coverage && (
          <VideoCoverageNote coverage={courseStatus.video_coverage} />
        )}
      </div>
    );
  }

  // "View Course" — content is ready and we're in idle state
  if (courseStatus?.status === "ready" && localState === "idle") {
    return (
      <div>
        <button
          type="button"
          onClick={handleClick}
          className="inline-flex items-center gap-1.5 border border-brand-primary text-brand-primary hover:bg-brand-primary hover:text-white rounded-full px-4 py-1.5 text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary focus-visible:ring-offset-2"
          aria-label="View mini-course content for this topic"
        >
          <BookOpen className="w-3.5 h-3.5" aria-hidden="true" />
          View Course
        </button>
        {courseStatus.video_coverage && (
          <VideoCoverageNote coverage={courseStatus.video_coverage} />
        )}
      </div>
    );
  }

  // Default: "Generate Mini-Course" (none or failed state, idle local)
  if (localState === "confirming") {
    return (
      <span className="text-xs text-brand-muted italic" aria-live="polite">
        This will generate AI explanations for all subtopics...
      </span>
    );
  }

  return (
    <button
      type="button"
      onClick={handleClick}
      disabled={localState === "pending"}
      className="inline-flex items-center gap-1.5 border border-brand-gold text-brand-gold hover:bg-brand-gold hover:text-white disabled:opacity-60 disabled:cursor-not-allowed rounded-full px-4 py-1.5 text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-gold focus-visible:ring-offset-2"
      aria-label="Generate AI mini-course content for this topic"
    >
      {localState === "pending" ? (
        <>
          <Loader2 className="w-3.5 h-3.5 animate-spin" aria-hidden="true" />
          Generating...
        </>
      ) : (
        <>
          <Sparkles className="w-3.5 h-3.5" aria-hidden="true" />
          Generate Mini-Course
        </>
      )}
    </button>
  );
}
