FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

# Point to the mounted store location
ENV PNPM_HOME=/app/.pnpm-store

EXPOSE 3001

CMD ["sh", "-c", "rm -rf /app/apps/teacher/node_modules/.vite && pnpm install --config.confirmModulesPurge=false && pnpm dev:teacher"]
